vich_uploader:
    db_driver: orm

    mappings:
        gdo_image:
            uri_prefix: /images/gdo
            upload_destination: '%kernel.project_dir%/public/images/gdo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

